name: vfdl

# The package version.  See the Haskell package versioning policy (PVP)
# for standards guiding when and how versions should be incremented.
# https://wiki.haskell.org/Package_versioning_policy
# PVP summary:      +-+------- breaking API changes
#                   | | +----- non-breaking API additions
#                   | | | +--- code changes with no API change
version: 0.0.1.0

synopsis: A hardware description language for factorio factories

description: See README at <https://github.com/dequbed/facdsl#readme>

license: GPL-3
license-file: LICENSE

author: Nadja Reitzenstein <me@dequbed.space>
maintainer: Nadja Reitzenstein <me@dequbed.space>
github: dequbed/vfdl

category: Development

extra-source-files:
  - README.md
  - CHANGELOG.md

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

dependencies:
  - base >= 4.9 && < 5
  - parsec >= 3.1 && < 4
  - text >= 1.2 && < 1.3

library:
  source-dirs: src
  exposed-modules:
    - Prelude
    - Language.VFDL
  dependencies:
    - name: base
      version: ">= 4.13 && <5"
      mixin: &base-mixin
        - hiding (Prelude)
    - name: rio
      version: ">= 0.1  && <1"
      mixin: &rio-mixin
        - (RIO as RIO)
        - (RIO.List                     as Prelude.List)
        - (RIO.ByteString               as Prelude.ByteString)
        - (RIO.ByteString.Lazy          as Prelude.ByteString.Lazy)
        - (RIO.ByteString.Lazy.Partial  as Prelude.ByteString.Lazy.Partial)
        - (RIO.ByteString.Partial       as Prelude.ByteString.Partial)
        - (RIO.Char                     as Prelude.Char)
        - (RIO.Char.Partial             as Prelude.Char.Partial)
        - (RIO.Deque                    as Prelude.Deque)
        - (RIO.Directory                as Prelude.Directory)
        - (RIO.File                     as Prelude.File)
        - (RIO.FilePath                 as Prelude.FilePath)
        - (RIO.HashMap                  as Prelude.HashMap)
        - (RIO.HashMap.Partial          as Prelude.HashMap.Partial)
        - (RIO.HashSet                  as Prelude.HashSet)
        - (RIO.List                     as Prelude.List)
        - (RIO.List.Partial             as Prelude.List.Partial)
        - (RIO.Map                      as Prelude.Map)
        - (RIO.Map.Partial              as Prelude.Map.Partial)
        - (RIO.Map.Unchecked            as Prelude.Map.Unchecked)
        - (RIO.NonEmpty                 as Prelude.NonEmpty)
        - (RIO.NonEmpty.Partial         as Prelude.NonEmpty.Partial)
        - (RIO.Partial                  as Prelude.Partial)
        - (RIO.Prelude                  as Prelude.Prelude)
        - (RIO.Prelude.Simple           as Prelude.Prelude.Simple)
        - (RIO.Prelude.Types            as Prelude.Prelude.Types)
        - (RIO.Process                  as Prelude.Process)
        - (RIO.Seq                      as Prelude.Seq)
        - (RIO.Set                      as Prelude.Set)
        - (RIO.Set.Partial              as Prelude.Set.Partial)
        - (RIO.Set.Unchecked            as Prelude.Set.Unchecked)
        - (RIO.State                    as Prelude.State)
        - (RIO.Text                     as Prelude.Text)
        - (RIO.Text.Lazy                as Prelude.Text.Lazy)
        - (RIO.Text.Lazy.Partial        as Prelude.Text.Lazy.Partial)
        - (RIO.Text.Partial             as Prelude.Text.Partial)
        - (RIO.Time                     as Prelude.Time)
        - (RIO.Vector                   as Prelude.Vector)
        - (RIO.Vector.Boxed             as Prelude.Vector.Boxed)
        - (RIO.Vector.Boxed.Partial     as Prelude.Vector.Boxed.Partial)
        - (RIO.Vector.Boxed.Unsafe      as Prelude.Vector.Boxed.Unsafe)
        - (RIO.Vector.Partial           as Prelude.Vector.Partial)
        - (RIO.Vector.Storable          as Prelude.Vector.Storable)
        - (RIO.Vector.Storable.Partial  as Prelude.Vector.Storable.Partial)
        - (RIO.Vector.Storable.Unsafe   as Prelude.Vector.Storable.Unsafe)
        - (RIO.Vector.Unboxed           as Prelude.Vector.Unboxed)
        - (RIO.Vector.Unboxed.Partial   as Prelude.Vector.Unboxed.Partial)
        - (RIO.Vector.Unboxed.Unsafe    as Prelude.Vector.Unboxed.Unsafe)
        - (RIO.Vector.Unsafe            as Prelude.Vector.Unsafe)
        - (RIO.Writer                   as Prelude.Writer)
    - aeson >= 1.5 && < 1.6

executables:
  vfdlc:
    main: Main.hs
    source-dirs: app
    dependencies:
      - name: base
        version: ">= 4.13 && <4.15"
        mixin: *base-mixin
      - name: rio
        version: ">= 0.1  && <0.2"
        mixin: *rio-mixin
      - vfdl
      - cabal-file-th >= 0.2 && <0.3

# vim: nospell
